name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  my_first_job:
    
      name: Jobs to update datas
      runs-on: ubuntu-latest
      steps:
      # Snake Animation
        - uses: Platane/snk@master
          id: snake-gif

          with:
            github_user_name: eagrundy
            svg_out_path: dist/github-contribution-grid-snake.svg
        - uses: crazy-max/ghaction-github-pages@v2.1.3
          with:
            target_branch: output
            build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  my_second_job:
    
      runs-on: ubuntu-latest
      name: generate-github-profile-3d-contrib
      steps:
        - uses: actions/checkout@v3
        - uses: yoshi389111/github-profile-3d-contrib@0.7.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            USERNAME: ${{ github.repository_owner }}
        - name: Commit & Push
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add -A .
            git commit -m "generated"
            git push
